title: Zahra Febrilia Rachmawati # your name (or website title) here
logo: "/photo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Majoring of Mathematics at Sebelas Maret University
  <br><br>
  <a href="https://www.linkedin.com/in/zahra-febrilia-956aab1b3">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
